require("core.keymaps")
require("core.options")

require("plugins._plugins")
require("plugins.colorscheme")
require("plugins.telescope")
require("plugins.lualine")
require("plugins.alpha")
require("plugins.nvim-tree")
require("plugins.whichkey")
require("plugins.bufferline")
require("plugins.cmp")
require("plugins.autopairs")
require("plugins.lsp")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("plugins.colorizer")
require("plugins.gitsigns")
require("plugins.comment")
require("plugins.trouble")
require("plugins.indent-blankline")
require("plugins.toggleterm")

require("matt.globals")
